language: android
jdk: openjdk8
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-P

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - ./gradlew clean lint
  - checkStyleVer=8.10
  - wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-$checkStyleVer/checkstyle-$checkStyleVer-all.jar --quiet
  - java -jar checkstyle-$checkStyleVer-all.jar -c config/checkstyle/checkstyle.xml app/src/ -o checkstyle-results.txt
  - echo "\n\n\n\n====================================================="
  - echo "checkstyle result"
  - cat checkstyle-results.txt | nc termbin.com 9999
  - rm checkstyle-$checkStyleVer-all.jar

script:
  - ./gradlew clean build

after_script:
  - echo "\n\n\n\n====================================================="
  - echo "lint results"
  - cat app/build/reports/lint-results.html | nc termbin.com 9999